services:
  postgres:
    image: postgres:16-alpine
    container_name: kalba-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kalba
    ports:
      - "5432:5432"
    volumes:
      - kalba_pg_data:/var/lib/postgresql/data

volumes:
  kalba_pg_data:
